#!/bin/bash
#set -x

USER=$(id -nu)
DIR=$(pwd)
CMD="git clone"
CLONE_FILE="${HOME}/.gc"
PROJECT_NAME=""

usage()
{
  echo "Usage: "
  echo "  $0 git_url"
  echo "  $0 cd repo_number"
  echo "  $0 ls|-l"
  echo "  $0 -d project"
  exit 1
}

show_clones()
{
  [[ -e ${CLONE_FILE} ]] && more ${CLONE_FILE} && return 0
}

# Append repo in CLONE_FILE
write_clonefile()
{
  PROJECT_NAME=$(get_project_name $1)
  if grep $PROJECT_NAME $CLONE_FILE > /dev/null
  then
    echo "$PROJECT_NAME is existing..."
    return
  fi
  num=$(awk '/./{line=$0} END{print $1}' $CLONE_FILE)
  num=$((num+1))
  echo "$num $PROJECT_NAME $1 $DIR/$PROJECT_NAME" >> $CLONE_FILE
}

# Remove repo in CLONE_FILE
remove_repo()
{
  echo "remove repo $1"
  repo=$1
  dir=$(awk -v "name=$repo" '$2==name {print $NF}' < $CLONE_FILE)

  re_num='^[0-9]+$'
  if [[ $repo =~ $re_num ]]
  then
    sed -i "/^$repo\ /d" ~/.gc
  else
    tmpfile=$(mktemp)
    awk -v "name=$repo" '$2!=name {print $0}' $CLONE_FILE > $tmpfile
    mv $tmpfile $CLONE_FILE
  fi

  [[ "$dir" != "/" && "$dir" != "" ]] && rm -fr $dir
}

# Retrieve project name from repo url
get_project_name()
{
  git_url="$1"
  if [[ "$git_url" =~ \.git$ ]]
  then
    echo $(sed 's/.*\/\(.*\)\.git/\1/' <<< "$git_url")
  else
    echo $(sed 's/.*\/\(.*\)/\1/' <<< "$git_url")
  fi
}

chdir()
{
  dir=$(awk -v "num=$1" '$1==num {print $NF}' < $CLONE_FILE)
  cd $dir
  exec bash
}

scandir()
{
  scan_dir=$1
  if [ "$scan_dir" == "" ]
  then 
    scan_dir="."
  fi

  ls -d ${scan_dir}/*/ | while read dir
  do
    (
      cd $dir
      git_url=$(git config -l | grep remote.origin.url)
      git_url=${git_url#*=}
      write_clonefile $git_url
    )
  done
}

case "$1" in
  cd)
    # Change directory
    if [ "$2" == "" ]
    then
      usage
    else
      chdir $2
      exit 0
    fi
    ;;
  ls)
    show_clones
    exit 0
    ;;
esac

[[ ! -e $CLONE_FILE ]] && touch $CLONE_FILE

while getopts "hsld:f:" arg; do
  case $arg in
    h)
      usage 
      ;;
    f)
      clone_file=${OPTARG}
      ;;
    d)
      repo_name=${OPTARG}
      ;;
    l)
      show_clones
      exit 0
      ;;
    s)
      willScan=true
      dir=${OPTARG}
      ;;
  esac
done
shift $((OPTIND-1))

[[ "$willScan" == true ]] && scandir $dir && exit 0
[[ "$repo_name" != "" ]] && remove_repo $repo_name && exit 0

[[ $1 == "" ]] && usage
repo_url="$1"

if [ "$repo_url" == "" ]
then
  usage
fi

PROJECT_NAME=$(get_project_name $repo_url)

if [ $(grep -c $repo_url $CLONE_FILE) == 0 ]
then
  echo "Not cloned yet!"
else
  echo "Cloned in CLONE_FILE!"
  exit 1
fi

eval $CMD $1
if [[ $? != 0 ]]
then
  echo "Failed to clone repo!"
else
  write_clonefile "$repo_url"
fi
